//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DauGia
    {
        public int ID_DauGia { get; set; }
        public Nullable<int> ID_SanPham { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> Gia { get; set; }
    }
}
