//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProID { get; set; }
        public string ProName { get; set; }
        public string TinyDes { get; set; }
        public Nullable<decimal> PriceCurrent { get; set; }
        public Nullable<decimal> PriceNow { get; set; }
        public Nullable<System.DateTime> TimeRemain { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string NameSale { get; set; }
        public Nullable<System.DateTime> TimePost { get; set; }
        public Nullable<System.DateTime> TimeUp { get; set; }
        public Nullable<int> CatID { get; set; }
        public Nullable<int> ImgID { get; set; }
    }
}
